### ISSUE TITLE
About the Gurobi

### ISSUE THREAD

**Issue by YiruWangYuri** [ZhipengCai/Demo---Deterministic-consensus-maximization-with-biconvex-programming#1]
The Guribo will speed up the algorithm. However, it seems that the IBCO part doesn't use the gurobiLinProg.m or gurobiQuadProg.m. It means that even though I change the variable solver.LP ='guribo' or solver.socp='guribo' in demo.m, it still finish the optimization with sedumi toolbox.

**Comment by ZhipengCai** [comment]
> The Guribo will speed up the algorithm. However, it seems that the IBCO part doesn't use the gurobiLinProg.m or gurobiQuadProg.m. It means that even though I change the variable solver.LP ='guribo' or solver.socp='guribo' in demo.m, it still finish the optimization with sedumi toolbox.

Yes current version of IBCO does not use Gurobi for solving LP and SOCP, what I mean by “speed up the algortithm” is that Gurobi can speed up other deterministic methods, such as EP in the demo. Switching solver.lp or solver.socp to Gurobi only affects those methods so that you can reproduce the relative runtime in our paper.
 
Still, it is possible to use gurobi in IBCO, you can always change my implementation and feed the LP or SOCP problem in IBCO to gurobi solvers.
